server:
  port: 8081

hikari:
  book:
    jdbcUrl: jdbc:mysql://boying_dev:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

  user:
    jdbcUrl: jdbc:mysql://boying_dev:3306/user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver


